wip envfile

diff --git a/docker/production/Dockerfile-frontend b/docker/production/Dockerfile-frontend
--- a/docker/production/Dockerfile-frontend
+++ b/docker/production/Dockerfile-frontend
@@ -10,11 +10,11 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY frontend-server/package.json frontend-server/package-lock.json  ./
 RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 
 # 2. Rebuild the source code only when needed
